export const CARD_REQUEST_PROFESSIONS = [
  "Administrador",
  "Advogado",
  "Agente comercial",
  "Agente de segurança",
  "Agente de viagens",
  "Agricultor",
  "Agrônomo",
  "Analista administrativo",
  "Analista comercial",
  "Analista contábil",
  "Analista de atendimento",
  "Analista de crédito",
  "Analista de dados",
  "Analista de marketing",
  "Analista de recursos humanos",
  "Analista de sistemas",
  "Analista financeiro",
  "Arquiteto",
  "Artesão",
  "Assistente administrativo",
  "Assistente comercial",
  "Assistente contábil",
  "Assistente de atendimento",
  "Assistente financeiro",
  "Assistente social",
  "Atendente",
  "Atendente de loja",
  "Autônomo",
  "Auxiliar administrativo",
  "Auxiliar contábil",
  "Auxiliar de cozinha",
  "Auxiliar de enfermagem",
  "Auxiliar de limpeza",
  "Auxiliar de logística",
  "Auxiliar de produção",
  "Babá",
  "Bancário",
  "Barbeiro",
  "Cabeleireiro",
  "Caixa",
  "Caminhoneiro",
  "Chef de cozinha",
  "Comerciante",
  "Comprador",
  "Confeiteiro",
  "Consultor",
  "Consultor comercial",
  "Consultor financeiro",
  "Contador",
  "Corretor de imóveis",
  "Corretor de seguros",
  "Costureira",
  "Cozinheiro",
  "Cuidador de idosos",
  "Dentista",
  "Designer",
  "Designer gráfico",
  "Desenvolvedor de software",
  "Diarista",
  "Diretor",
  "Educador físico",
  "Eletricista",
  "Empregada doméstica",
  "Empresário",
  "Encanador",
  "Enfermeiro",
  "Engenheiro",
  "Entregador",
  "Escriturário",
  "Esteticista",
  "Estudante",
  "Farmacêutico",
  "Faxineiro",
  "Fisioterapeuta",
  "Fotógrafo",
  "Freelancer",
  "Garçom",
  "Gerente",
  "Gerente administrativo",
  "Gerente comercial",
  "Gerente financeiro",
  "Influenciador digital",
  "Instalador",
  "Jardineiro",
  "Jornalista",
  "Manicure",
  "Marceneiro",
  "Mecânico",
  "Médico",
  "MEI",
  "Militar",
  "Motorista",
  "Motorista de aplicativo",
  "Nutricionista",
  "Operador de caixa",
  "Operador de máquinas",
  "Operador de telemarketing",
  "Padeiro",
  "Pedagogo",
  "Pedreiro",
  "Pintor",
  "Porteiro",
  "Professor",
  "Programador",
  "Promotor de vendas",
  "Psicólogo",
  "Publicitário",
  "Recepcionista",
  "Representante comercial",
  "Segurança",
  "Servidor público",
  "Social media",
  "Supervisor",
  "Taxista",
  "Técnico administrativo",
  "Técnico de enfermagem",
  "Técnico de informática",
  "Técnico eletricista",
  "Técnico mecânico",
  "Telemarketing",
  "Terapeuta",
  "Vendedor",
  "Veterinário",
  "Vigilante",
  "Outros",
] as const;
