import { randomToken } from "@/lib/credit/helpers";
import type { CreditWizardDraft, WizardMode } from "@/components/credito/types";

export function createDefaultDraft(mode: WizardMode): CreditWizardDraft {
  return {
    mode,
    account: {
      name: "",
      email: "",
      password: "",
      phone: "",
    },
    consent: {
      consentDataProcessing: false,
      consentContact: false,
      consentTrueInfo: false,
      consentPrivacyPolicy: false,
      consentCreditQuery: false,
    },
    address: {
      zipcode: "",
      street: "",
      number: "",
      complement: "",
      district: "",
      city: "",
      state: "",
    },
    bank: {
      bank: "",
      agency: "",
      account: "",
      accountDigit: "",
      accountType: "",
      holderName: "",
      holderDocument: "",
      pixKey: "",
      ownershipConfirmed: false,
    },
    request: {
      requestedAmount: 6500,
      desiredTerm: 12,
      desiredDueDay: 10,
      purpose: "Outro",
      notes: "",
    },
    documents: [],
    pfData: {
      fullName: "",
      cpf: "",
      birthDate: "",
      motherName: "",
      maritalStatus: "",
      nationality: "Brasileira",
      email: "",
      whatsapp: "",
      profession: "",
      incomeType: "",
      monthlyIncome: 0,
      incomeTime: "",
      hasRestrictions: false,
      hasActiveLoans: false,
      currentInstallmentsAmount: 0,
    },
    meiData: {
      responsibleName: "",
      responsibleCpf: "",
      responsibleBirthDate: "",
      responsibleEmail: "",
      responsibleWhatsapp: "",
      cnpj: "",
      legalName: "",
      tradeName: "",
      openingDate: "",
      cnae: "",
      activity: "",
      monthlyRevenue: 0,
      yearlyRevenue: 0,
      segment: "",
    },
    pjData: {
      cnpj: "",
      legalName: "",
      tradeName: "",
      companyType: "",
      openingDate: "",
      cnae: "",
      segment: "",
      monthlyRevenue: 0,
      yearlyRevenue: 0,
      employeesCount: 0,
      expensesMonthly: 0,
      averageProfit: 0,
      hasActiveLoans: false,
      currentInstallmentsAmount: 0,
      hasBusinessRestrictions: false,
      hasPartnerRestrictions: false,
    },
    partners: [
      {
        name: "",
        cpf: "",
        ownershipPercent: 0,
        email: "",
        whatsapp: "",
        isAdministrator: true,
      },
    ],
  };
}

export function createLocalDocumentId() {
  return `doc_${randomToken(10)}`;
}
